[project]
name = 'Decentralized-Energy-Trading-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-certificate-nft]
path = 'contracts/energy-certificate-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-listing]
path = 'contracts/energy-listing.clar'
clarity_version = 2
epoch = 2.5

[contracts.smart-meter-integration]
path = 'contracts/smart-meter-integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
